/**
 * ✅ ENTELECHIA INVARIANT ENGINE — Domain Invariants
 * 
 * Domain-specific invariants for business logic, state management, and data consistency.
 */

import { registry } from '../../core/registry'

// Import domain invariants
import { F68_DASHBOARD_HEADER_UNIVERSALITY } from './F68_DASHBOARD_HEADER_UNIVERSALITY'
import { F82_MUTATION_STATEVIEW_SYNCHRONY } from './F82_MUTATION_STATEVIEW_SYNCHRONY'
import { F2_SYSTEM_STATE_VIEW_SINGULAR } from './F2_SYSTEM_STATE_VIEW_SINGULAR'
import { F76_REFRESH_PROMPT_REQUIRED } from './F76_REFRESH_PROMPT_REQUIRED'
import { F27_SESSION_CONTINUITY } from './F27_SESSION_CONTINUITY'
import { F28_NO_HARD_EXPIRY_WITHOUT_REFRESH } from './F28_NO_HARD_EXPIRY_WITHOUT_REFRESH'
import { F1_TEXT_ID_IS_FORM } from './F1_TEXT_ID_IS_FORM'
import { F3_ROUTER_GUARD_DETERMINISTIC } from './F3_ROUTER_GUARD_DETERMINISTIC'
import { F4_NODE_DEFINITIONS_ABSOLUTE } from './F4_NODE_DEFINITIONS_ABSOLUTE'
import { F5_AUTH_SINGLE_SOURCE_OF_TRUTH } from './F5_AUTH_SINGLE_SOURCE_OF_TRUTH'
import { F6_IMMUTABLE_SESSION_CONTRACT } from './F6_IMMUTABLE_SESSION_CONTRACT'
import { F25_NO_FLASH_BLINK } from './F25_NO_FLASH_BLINK'
import { I16_BACKEND_READINESS_CHECK } from './I16_BACKEND_READINESS_CHECK'
import { I19_NO_AUTH_RACE_CONDITIONS } from './I19_NO_AUTH_RACE_CONDITIONS'
import { I12_NAVIGATION_MUST_BE_SYNCHRONOUS } from './I12_NAVIGATION_MUST_BE_SYNCHRONOUS'
import { I13_NO_AWAIT_FOR_CACHE_OPERATIONS } from './I13_NO_AWAIT_FOR_CACHE_OPERATIONS'
import { I15_NO_NAVIGATION_IN_CALLBACKS } from './I15_NO_NAVIGATION_IN_CALLBACKS'
import { A7_AUTHCACHE_MIRRORS_SSOT } from './A7_AUTHCACHE_MIRRORS_SSOT'
import { A11_AUTH_SETTLE_TIMEOUT } from './A11_AUTH_SETTLE_TIMEOUT'
import { A1_AUTH_NO_HARD_NAVIGATIONS } from './A1_AUTH_NO_HARD_NAVIGATIONS'
import { A1_WORKSPACE_VIEW_ONLY_READS } from './A1_WORKSPACE_VIEW_ONLY_READS'
import { A2_AUTH_SPA_IDENTITY_PRESERVATION } from './A2_AUTH_SPA_IDENTITY_PRESERVATION'
import { A3_NO_DOUBLE_MOUNTS } from './A3_NO_DOUBLE_MOUNTS'
import { E0_EMPTY_STATE } from './E0_EMPTY_STATE'
import { F29_REFRESH_STABILITY } from './F29_REFRESH_STABILITY'
import { E6_ZERO_FLICKER_LOGIN } from './E6_ZERO_FLICKER_LOGIN'
import { E8_INTENT_PRELOAD } from './E8_INTENT_PRELOAD'
import { E10_LOGIN_LATENCY } from './E10_LOGIN_LATENCY'
import { F9_UNAUTHORIZED_REDIRECT } from './F9_UNAUTHORIZED_REDIRECT'

// Export all domain invariants
export {
  F68_DASHBOARD_HEADER_UNIVERSALITY,
  F82_MUTATION_STATEVIEW_SYNCHRONY,
  F2_SYSTEM_STATE_VIEW_SINGULAR,
  F76_REFRESH_PROMPT_REQUIRED,
  F27_SESSION_CONTINUITY,
  F28_NO_HARD_EXPIRY_WITHOUT_REFRESH,
  F1_TEXT_ID_IS_FORM,
  F3_ROUTER_GUARD_DETERMINISTIC,
  F4_NODE_DEFINITIONS_ABSOLUTE,
  F5_AUTH_SINGLE_SOURCE_OF_TRUTH,
  F6_IMMUTABLE_SESSION_CONTRACT,
  F25_NO_FLASH_BLINK,
  I16_BACKEND_READINESS_CHECK,
  I19_NO_AUTH_RACE_CONDITIONS,
  I12_NAVIGATION_MUST_BE_SYNCHRONOUS,
  I13_NO_AWAIT_FOR_CACHE_OPERATIONS,
  I15_NO_NAVIGATION_IN_CALLBACKS,
  A7_AUTHCACHE_MIRRORS_SSOT,
  A11_AUTH_SETTLE_TIMEOUT,
  A1_AUTH_NO_HARD_NAVIGATIONS,
  A1_WORKSPACE_VIEW_ONLY_READS,
  A2_AUTH_SPA_IDENTITY_PRESERVATION,
  A3_NO_DOUBLE_MOUNTS,
  E0_EMPTY_STATE,
  F29_REFRESH_STABILITY,
  E6_ZERO_FLICKER_LOGIN,
  E8_INTENT_PRELOAD,
  E10_LOGIN_LATENCY,
  F9_UNAUTHORIZED_REDIRECT,
}

// Auto-register all invariants
const INVARIANTS = [
  F68_DASHBOARD_HEADER_UNIVERSALITY,
  F82_MUTATION_STATEVIEW_SYNCHRONY,
  F2_SYSTEM_STATE_VIEW_SINGULAR,
  F76_REFRESH_PROMPT_REQUIRED,
  F27_SESSION_CONTINUITY,
  F28_NO_HARD_EXPIRY_WITHOUT_REFRESH,
  F1_TEXT_ID_IS_FORM,
  F3_ROUTER_GUARD_DETERMINISTIC,
  F4_NODE_DEFINITIONS_ABSOLUTE,
  F5_AUTH_SINGLE_SOURCE_OF_TRUTH,
  F6_IMMUTABLE_SESSION_CONTRACT,
  F25_NO_FLASH_BLINK,
  I16_BACKEND_READINESS_CHECK,
  I19_NO_AUTH_RACE_CONDITIONS,
  I12_NAVIGATION_MUST_BE_SYNCHRONOUS,
  I13_NO_AWAIT_FOR_CACHE_OPERATIONS,
  I15_NO_NAVIGATION_IN_CALLBACKS,
  A7_AUTHCACHE_MIRRORS_SSOT,
  A11_AUTH_SETTLE_TIMEOUT,
  A1_AUTH_NO_HARD_NAVIGATIONS,
  A1_WORKSPACE_VIEW_ONLY_READS,
  A2_AUTH_SPA_IDENTITY_PRESERVATION,
  A3_NO_DOUBLE_MOUNTS,
  E0_EMPTY_STATE,
  F29_REFRESH_STABILITY,
  E6_ZERO_FLICKER_LOGIN,
  E8_INTENT_PRELOAD,
  E10_LOGIN_LATENCY,
  F9_UNAUTHORIZED_REDIRECT,
]

// Register all invariants
INVARIANTS.forEach(invariant => {
  try {
    // Generate filename: preserve prefix (F, I, A, etc.) and append name
    const codePrefix = invariant.code.match(/^[A-Z]+/)?.[0] || 'F'
    const codeNumber = invariant.code.replace(/^[A-Z]+/, '')
    const fileName = `${codePrefix}${codeNumber}_${invariant.name.replace(/\s+/g, '_').toUpperCase()}.ts`
    registry.register(invariant, `packages/invariant-engine/src/invariants/domain/${fileName}`)
  } catch (error) {
    // Ignore collision errors (invariant already registered)
    if (!(error instanceof Error && (error.message.includes('already exists') || error.message.includes('collision')))) {
      console.error(`Failed to register invariant ${invariant.category}.${invariant.code}:`, error)
    }
  }
})
