/**
 * ✅ ENTELECHIA INVARIANT ENGINE — System Invariants
 * 
 * All system-related invariants are exported from here.
 * Individual invariant files are imported and re-exported.
 * 
 * All invariants are automatically registered when this module is imported.
 */

import { registry } from '../../core/registry'

// Import all system invariants
import { F12_SEQUENTIAL_RENDER_ORDER } from './F12_SEQUENTIAL_RENDER_ORDER'
import { F32_ZERO_PLACEHOLDER_FIRST_FRAME } from './F32_ZERO_PLACEHOLDER_FIRST_FRAME'
import { F33_SNAPSHOT_ATOMARITY } from './F33_SNAPSHOT_ATOMARITY'
import { F34_SNAPSHOT_PRIORITY_OVERRIDES_NETWORK } from './F34_SNAPSHOT_PRIORITY_OVERRIDES_NETWORK'
import { F35_OFFLINE_HYDRATION_COMPATIBILITY } from './F35_OFFLINE_HYDRATION_COMPATIBILITY'
import { F36_NODE_SELECTION_ALIGNED_WITH_URL } from './F36_NODE_SELECTION_ALIGNED_WITH_URL'
import { F37_NODE_SELECTION_ATOMICITY } from './F37_NODE_SELECTION_ATOMICITY'
import { F38_NODE_STATEVIEW_STABILITY } from './F38_NODE_STATEVIEW_STABILITY'
import { F39_ROUTER_GUARD_SNAPSHOT_ALIGNMENT } from './F39_ROUTER_GUARD_SNAPSHOT_ALIGNMENT'
import { F40_VIEWMODEL_PERSISTENCE_BASELINE } from './F40_VIEWMODEL_PERSISTENCE_BASELINE'
import { F41_VIEWMODEL_NO_PLACEHOLDER_ALLOWED } from './F41_VIEWMODEL_NO_PLACEHOLDER_ALLOWED'
import { F42_VIEWMODEL_STABLE_IDENTITY } from './F42_VIEWMODEL_STABLE_IDENTITY'
import { F43_SYSTEMSTATEVIEW_PERSISTENCE } from './F43_SYSTEMSTATEVIEW_PERSISTENCE'
import { F44_SYSTEMSTATEVIEW_NO_RELOAD_FLICKER } from './F44_SYSTEMSTATEVIEW_NO_RELOAD_FLICKER'
import { F45_AUTH_PERSISTENCE_FIRST_FRAME } from './F45_AUTH_PERSISTENCE_FIRST_FRAME'
import { F46_AUTH_SILENT_REHYDRATION } from './F46_AUTH_SILENT_REHYDRATION'
import { F47_NO_GLOBAL_REMOUNT } from './F47_NO_GLOBAL_REMOUNT'
import { F48_ZERO_WAIT_INTERACTIONS } from './F48_ZERO_WAIT_INTERACTIONS'
import { F49_ZERO_INVISIBLE_RENDERS } from './F49_ZERO_INVISIBLE_RENDERS'
import { F50_TOTAL_ONTOLOGICAL_UI_COHERENCE } from './F50_TOTAL_ONTOLOGICAL_UI_COHERENCE'
import { F55_ROUTER_NO_HARD_REFRESH } from './F55_ROUTER_NO_HARD_REFRESH'
import { F91_COMMAND_INTENT_BINDING_COHERENCE } from './F91_COMMAND_INTENT_BINDING_COHERENCE'
import { ARCHITECTURE_F01_FORBIDDEN_UI_ACT_HOOK } from './ARCHITECTURE_F01_FORBIDDEN_UI_ACT_HOOK'
import { I01_INTENT_EXISTS } from './I01_INTENT_EXISTS'
import { I02_ACTION_EXISTS } from './I02_ACTION_EXISTS'
import { I03_INVARIANT_EXISTS } from './I03_INVARIANT_EXISTS'
import { I04_METRIC_EXISTS } from './I04_METRIC_EXISTS'
import { I05_GRAPH_ACYCLIC } from './I05_GRAPH_ACYCLIC'
import { I06_NO_ORPHANS } from './I06_NO_ORPHANS'
import { INTENT_F55_EXECUTOR_CANNOT_BE_HOOK } from './INTENT_F55_EXECUTOR_CANNOT_BE_HOOK'
import { ACT_F99_REROUTE_DETECTED } from './ACT_F99_REROUTE_DETECTED'
import { ACT_F60_PAYLOAD_MISMATCH } from './ACT_F60_PAYLOAD_MISMATCH'
import { ACT_F61_CONTEXT_MISMATCH } from './ACT_F61_CONTEXT_MISMATCH'
import { SURFACE_F01_NO_ADHOC_UI_IN_META_REPOS } from './SURFACE_F01_NO_ADHOC_UI_IN_META_REPOS'
import { SURFACE_F02_ALL_META_VIEWS_HAVE_FORM_SOURCE } from './SURFACE_F02_ALL_META_VIEWS_HAVE_FORM_SOURCE'
import { SURFACE_F03_SURFACE_RENDERER_ONLY_CANONICAL_BLOCKS } from './SURFACE_F03_SURFACE_RENDERER_ONLY_CANONICAL_BLOCKS'

// Export all invariants
export {
  F12_SEQUENTIAL_RENDER_ORDER,
  F32_ZERO_PLACEHOLDER_FIRST_FRAME,
  F33_SNAPSHOT_ATOMARITY,
  F34_SNAPSHOT_PRIORITY_OVERRIDES_NETWORK,
  F35_OFFLINE_HYDRATION_COMPATIBILITY,
  F36_NODE_SELECTION_ALIGNED_WITH_URL,
  F37_NODE_SELECTION_ATOMICITY,
  F38_NODE_STATEVIEW_STABILITY,
  F39_ROUTER_GUARD_SNAPSHOT_ALIGNMENT,
  F40_VIEWMODEL_PERSISTENCE_BASELINE,
  F41_VIEWMODEL_NO_PLACEHOLDER_ALLOWED,
  F42_VIEWMODEL_STABLE_IDENTITY,
  F43_SYSTEMSTATEVIEW_PERSISTENCE,
  F44_SYSTEMSTATEVIEW_NO_RELOAD_FLICKER,
  F45_AUTH_PERSISTENCE_FIRST_FRAME,
  F46_AUTH_SILENT_REHYDRATION,
  F47_NO_GLOBAL_REMOUNT,
  F48_ZERO_WAIT_INTERACTIONS,
  F49_ZERO_INVISIBLE_RENDERS,
  F50_TOTAL_ONTOLOGICAL_UI_COHERENCE,
  F55_ROUTER_NO_HARD_REFRESH,
  F91_COMMAND_INTENT_BINDING_COHERENCE,
  ARCHITECTURE_F01_FORBIDDEN_UI_ACT_HOOK,
  I01_INTENT_EXISTS,
  I02_ACTION_EXISTS,
  I03_INVARIANT_EXISTS,
  I04_METRIC_EXISTS,
  I05_GRAPH_ACYCLIC,
  I06_NO_ORPHANS,
  INTENT_F55_EXECUTOR_CANNOT_BE_HOOK,
  ACT_F99_REROUTE_DETECTED,
  ACT_F60_PAYLOAD_MISMATCH,
  ACT_F61_CONTEXT_MISMATCH,
  SURFACE_F01_NO_ADHOC_UI_IN_META_REPOS,
  SURFACE_F02_ALL_META_VIEWS_HAVE_FORM_SOURCE,
  SURFACE_F03_SURFACE_RENDERER_ONLY_CANONICAL_BLOCKS,
}

// Auto-register all invariants
const INVARIANTS = [
  F12_SEQUENTIAL_RENDER_ORDER,
  F32_ZERO_PLACEHOLDER_FIRST_FRAME,
  F33_SNAPSHOT_ATOMARITY,
  F34_SNAPSHOT_PRIORITY_OVERRIDES_NETWORK,
  F35_OFFLINE_HYDRATION_COMPATIBILITY,
  F36_NODE_SELECTION_ALIGNED_WITH_URL,
  F37_NODE_SELECTION_ATOMICITY,
  F38_NODE_STATEVIEW_STABILITY,
  F39_ROUTER_GUARD_SNAPSHOT_ALIGNMENT,
  F40_VIEWMODEL_PERSISTENCE_BASELINE,
  F41_VIEWMODEL_NO_PLACEHOLDER_ALLOWED,
  F42_VIEWMODEL_STABLE_IDENTITY,
  F43_SYSTEMSTATEVIEW_PERSISTENCE,
  F44_SYSTEMSTATEVIEW_NO_RELOAD_FLICKER,
  F45_AUTH_PERSISTENCE_FIRST_FRAME,
  F46_AUTH_SILENT_REHYDRATION,
  F47_NO_GLOBAL_REMOUNT,
  F48_ZERO_WAIT_INTERACTIONS,
  F49_ZERO_INVISIBLE_RENDERS,
  F50_TOTAL_ONTOLOGICAL_UI_COHERENCE,
  F55_ROUTER_NO_HARD_REFRESH,
  F91_COMMAND_INTENT_BINDING_COHERENCE,
  ARCHITECTURE_F01_FORBIDDEN_UI_ACT_HOOK,
  I01_INTENT_EXISTS,
  I02_ACTION_EXISTS,
  I03_INVARIANT_EXISTS,
  I04_METRIC_EXISTS,
  I05_GRAPH_ACYCLIC,
  I06_NO_ORPHANS,
  INTENT_F55_EXECUTOR_CANNOT_BE_HOOK,
  ACT_F99_REROUTE_DETECTED,
  ACT_F60_PAYLOAD_MISMATCH,
  ACT_F61_CONTEXT_MISMATCH,
  SURFACE_F01_NO_ADHOC_UI_IN_META_REPOS,
  SURFACE_F02_ALL_META_VIEWS_HAVE_FORM_SOURCE,
  SURFACE_F03_SURFACE_RENDERER_ONLY_CANONICAL_BLOCKS,
]

// Register all invariants
INVARIANTS.forEach(invariant => {
  try {
    const fileName = `F${invariant.code.replace(/^F/, '')}_${invariant.name.replace(/\s+/g, '_').toUpperCase()}.ts`
    registry.register(invariant, `packages/invariant-engine/src/invariants/system/${fileName}`)
  } catch (error) {
    // Ignore collision errors (invariant already registered)
    if (!(error instanceof Error && (error.message.includes('already exists') || error.message.includes('collision')))) {
      console.error(`Failed to register invariant ${invariant.category}.${invariant.code}:`, error)
    }
  }
})
