/**
 * ✅ ENTELECHIA INVARIANT ENGINE — UI Invariants
 *
 * All UI-related invariants are exported from here.
 * Individual invariant files are imported and re-exported.
 *
 * All invariants are automatically registered when this module is imported.
 */
import { registry } from '../../core/registry';
// Import all UI invariants
import { F55_UI_FORM_IDENTITY } from './F55_UI_FORM_IDENTITY';
import { F56_SCROLL_LAW } from './F56_SCROLL_LAW';
import { F57_FRAME_PURITY_ENFORCED } from './F57_FRAME_PURITY_ENFORCED';
import { F58_VIEWPORT_SCROLL_PURITY } from './F58_VIEWPORT_SCROLL_PURITY';
import { F59_LAYOUT_TELEOLOGY_INVARIANT } from './F59_LAYOUT_TELEOLOGY_INVARIANT';
import { F60_SYSTEM_UI_ONTOLOGY } from './F60_SYSTEM_UI_ONTOLOGY';
import { F61_LAYOUT_UNITY } from './F61_LAYOUT_UNITY';
import { F62_FIXED_SIDEBAR_GEOMETRY } from './F62_FIXED_SIDEBAR_GEOMETRY';
import { F63_HEADER_SINGULARITY } from './F63_HEADER_SINGULARITY';
import { F64_SCROLL_CONSTRAINT } from './F64_SCROLL_CONSTRAINT';
import { F65_UI_FORMAL_INTEGRITY } from './F65_UI_FORMAL_INTEGRITY';
import { F66_GEOMETRIC_IDENTITY } from './F66_GEOMETRIC_IDENTITY';
import { F23_SIDEBAR_CANONICALITY } from './F23_SIDEBAR_CANONICALITY';
import { F24_NONDESTRUCTIVE_REFRESH_RENDERING } from './F24_NONDESTRUCTIVE_REFRESH_RENDERING';
import { F69_CROSS_VIEW_COGNITIVE_CONTINUITY } from './F69_CROSS_VIEW_COGNITIVE_CONTINUITY';
import { F77_VIEWPORT_IMMUTABILITY } from './F77_VIEWPORT_IMMUTABILITY';
import { F78_ROOT_SHELL_IDENTITY } from './F78_ROOT_SHELL_IDENTITY';
import { F79_DOMAIN_LAYOUT_IDENTITY } from './F79_DOMAIN_LAYOUT_IDENTITY';
import { F80_LAYOUT_NO_VOID_STATES } from './F80_LAYOUT_NO_VOID_STATES';
import { F81_PAGE_VERTICAL_EXPANSION } from './F81_PAGE_VERTICAL_EXPANSION';
import { F82_SINGLE_SCROLL_CONTAINER } from './F82_SINGLE_SCROLL_CONTAINER';
import { F83_BOUNDING_BOX_INTEGRITY } from './F83_BOUNDING_BOX_INTEGRITY';
import { F84_NAV_HIERARCHY_UNITY } from './F84_NAV_HIERARCHY_UNITY';
import { F85_TYPOGRAPHY_SCALE_UNITY } from './F85_TYPOGRAPHY_SCALE_UNITY';
import { F86_SPACING_GRID_UNITY } from './F86_SPACING_GRID_UNITY';
import { F87_SINGLE_SCROLL_CONTAINER_ACROSS_TRANSITIONS } from './F87_SINGLE_SCROLL_CONTAINER_ACROSS_TRANSITIONS';
import { F88_CHAT_LAYOUT_CONSTRAINTS } from './F88_CHAT_LAYOUT_CONSTRAINTS';
import { F89_SECTION_SCROLL_CANON } from './F89_SECTION_SCROLL_CANON';
import { F90_HEIGHT_CONSTRAINT_PURITY } from './F90_HEIGHT_CONSTRAINT_PURITY';
import { F91_TEMPORAL_UNITY } from './F91_TEMPORAL_UNITY';
import { F92_EASING_LAW } from './F92_EASING_LAW';
import { F93_STATE_TRANSITION_CONSISTENCY } from './F93_STATE_TRANSITION_CONSISTENCY';
import { F93_MICRO_LAYOUT_STABILITY } from './F93_MICRO_LAYOUT_STABILITY';
import { F94_COLOR_TRANSITION_INTEGRITY } from './F94_COLOR_TRANSITION_INTEGRITY';
import { F95_SPATIAL_TRANSITION_INTEGRITY } from './F95_SPATIAL_TRANSITION_INTEGRITY';
import { F96_MOTION_HIERARCHY_ALIGNMENT } from './F96_MOTION_HIERARCHY_ALIGNMENT';
import { F97_MOTION_IDENTITY_COHERENCE } from './F97_MOTION_IDENTITY_COHERENCE';
import { F98_CROSS_COMPONENT_MOTION_PARITY } from './F98_CROSS_COMPONENT_MOTION_PARITY';
import { F99_MOTION_PURITY } from './F99_MOTION_PURITY';
import { F100_FONT_FAMILY_UNITY } from './F100_FONT_FAMILY_UNITY';
import { F101_CANONICAL_TYPE_SCALE } from './F101_CANONICAL_TYPE_SCALE';
import { F102_WEIGHT_COHERENCE } from './F102_WEIGHT_COHERENCE';
import { F103_LINE_HEIGHT_INTEGRITY } from './F103_LINE_HEIGHT_INTEGRITY';
import { F104_HIERARCHY_DESCENT_LAW } from './F104_HIERARCHY_DESCENT_LAW';
import { F105_TOKENIZATION_CONSISTENCY } from './F105_TOKENIZATION_CONSISTENCY';
import { F106_STATE_BASED_TEXT_COLOR_RULES } from './F106_STATE_BASED_TEXT_COLOR_RULES';
import { F107_CROSS_COMPONENT_TYPOGRAPHIC_PARITY } from './F107_CROSS_COMPONENT_TYPOGRAPHIC_PARITY';
import { F108_NO_VISUAL_DOPPELGANGERS } from './F108_NO_VISUAL_DOPPELGANGERS';
import { F109_APPLE_LAYOUT_RHYTHM_COMPLIANCE } from './F109_APPLE_LAYOUT_RHYTHM_COMPLIANCE';
import { F110_APPLE_LAYOUT_RHYTHM_COMPLIANCE as F110_APPLE_LAYOUT_RHYTHM_COMPLIANCE } from './F110_APPLE_LAYOUT_RHYTHM_COMPLIANCE';
import { F001_FORM_SECTION_ORDERING } from './F001_FORM_SECTION_ORDERING';
import { F002_FORM_FIELD_SPACING } from './F002_FORM_FIELD_SPACING';
import { F003_FORM_WIDGET_APPROPRIATENESS } from './F003_FORM_WIDGET_APPROPRIATENESS';
import { F004_FORM_CANONICAL_PADDING } from './F004_FORM_CANONICAL_PADDING';
import { F005_FORM_SINGLE_SCROLL } from './F005_FORM_SINGLE_SCROLL';
// Export all invariants
export { F55_UI_FORM_IDENTITY, F56_SCROLL_LAW, F57_FRAME_PURITY_ENFORCED, F58_VIEWPORT_SCROLL_PURITY, F59_LAYOUT_TELEOLOGY_INVARIANT, F60_SYSTEM_UI_ONTOLOGY, F61_LAYOUT_UNITY, F62_FIXED_SIDEBAR_GEOMETRY, F63_HEADER_SINGULARITY, F64_SCROLL_CONSTRAINT, F65_UI_FORMAL_INTEGRITY, F66_GEOMETRIC_IDENTITY, F23_SIDEBAR_CANONICALITY, F24_NONDESTRUCTIVE_REFRESH_RENDERING, F69_CROSS_VIEW_COGNITIVE_CONTINUITY, F77_VIEWPORT_IMMUTABILITY, F78_ROOT_SHELL_IDENTITY, F79_DOMAIN_LAYOUT_IDENTITY, F80_LAYOUT_NO_VOID_STATES, F81_PAGE_VERTICAL_EXPANSION, F82_SINGLE_SCROLL_CONTAINER, F83_BOUNDING_BOX_INTEGRITY, F84_NAV_HIERARCHY_UNITY, F85_TYPOGRAPHY_SCALE_UNITY, F86_SPACING_GRID_UNITY, F87_SINGLE_SCROLL_CONTAINER_ACROSS_TRANSITIONS, F88_CHAT_LAYOUT_CONSTRAINTS, F89_SECTION_SCROLL_CANON, F90_HEIGHT_CONSTRAINT_PURITY, F91_TEMPORAL_UNITY, F92_EASING_LAW, F93_STATE_TRANSITION_CONSISTENCY, F93_MICRO_LAYOUT_STABILITY, F94_COLOR_TRANSITION_INTEGRITY, F95_SPATIAL_TRANSITION_INTEGRITY, F96_MOTION_HIERARCHY_ALIGNMENT, F97_MOTION_IDENTITY_COHERENCE, F98_CROSS_COMPONENT_MOTION_PARITY, F99_MOTION_PURITY, F100_FONT_FAMILY_UNITY, F101_CANONICAL_TYPE_SCALE, F102_WEIGHT_COHERENCE, F103_LINE_HEIGHT_INTEGRITY, F104_HIERARCHY_DESCENT_LAW, F105_TOKENIZATION_CONSISTENCY, F106_STATE_BASED_TEXT_COLOR_RULES, F107_CROSS_COMPONENT_TYPOGRAPHIC_PARITY, F108_NO_VISUAL_DOPPELGANGERS, F109_APPLE_LAYOUT_RHYTHM_COMPLIANCE, F110_APPLE_LAYOUT_RHYTHM_COMPLIANCE, F001_FORM_SECTION_ORDERING, F002_FORM_FIELD_SPACING, F003_FORM_WIDGET_APPROPRIATENESS, F004_FORM_CANONICAL_PADDING, F005_FORM_SINGLE_SCROLL, };
// Auto-register all invariants
const INVARIANTS = [
    F55_UI_FORM_IDENTITY,
    F56_SCROLL_LAW,
    F57_FRAME_PURITY_ENFORCED,
    F58_VIEWPORT_SCROLL_PURITY,
    F59_LAYOUT_TELEOLOGY_INVARIANT,
    F60_SYSTEM_UI_ONTOLOGY,
    F61_LAYOUT_UNITY,
    F62_FIXED_SIDEBAR_GEOMETRY,
    F63_HEADER_SINGULARITY,
    F64_SCROLL_CONSTRAINT,
    F65_UI_FORMAL_INTEGRITY,
    F66_GEOMETRIC_IDENTITY,
    F23_SIDEBAR_CANONICALITY,
    F24_NONDESTRUCTIVE_REFRESH_RENDERING,
    F69_CROSS_VIEW_COGNITIVE_CONTINUITY,
    F77_VIEWPORT_IMMUTABILITY,
    F78_ROOT_SHELL_IDENTITY,
    F79_DOMAIN_LAYOUT_IDENTITY,
    F80_LAYOUT_NO_VOID_STATES,
    F81_PAGE_VERTICAL_EXPANSION,
    F82_SINGLE_SCROLL_CONTAINER,
    F83_BOUNDING_BOX_INTEGRITY,
    F84_NAV_HIERARCHY_UNITY,
    F85_TYPOGRAPHY_SCALE_UNITY,
    F86_SPACING_GRID_UNITY,
    F87_SINGLE_SCROLL_CONTAINER_ACROSS_TRANSITIONS,
    F88_CHAT_LAYOUT_CONSTRAINTS,
    F89_SECTION_SCROLL_CANON,
    F90_HEIGHT_CONSTRAINT_PURITY,
    F91_TEMPORAL_UNITY,
    F92_EASING_LAW,
    F93_STATE_TRANSITION_CONSISTENCY,
    F93_MICRO_LAYOUT_STABILITY,
    F94_COLOR_TRANSITION_INTEGRITY,
    F95_SPATIAL_TRANSITION_INTEGRITY,
    F96_MOTION_HIERARCHY_ALIGNMENT,
    F97_MOTION_IDENTITY_COHERENCE,
    F98_CROSS_COMPONENT_MOTION_PARITY,
    F99_MOTION_PURITY,
    F100_FONT_FAMILY_UNITY,
    F101_CANONICAL_TYPE_SCALE,
    F102_WEIGHT_COHERENCE,
    F103_LINE_HEIGHT_INTEGRITY,
    F104_HIERARCHY_DESCENT_LAW,
    F105_TOKENIZATION_CONSISTENCY,
    F106_STATE_BASED_TEXT_COLOR_RULES,
    F107_CROSS_COMPONENT_TYPOGRAPHIC_PARITY,
    F108_NO_VISUAL_DOPPELGANGERS,
    F109_APPLE_LAYOUT_RHYTHM_COMPLIANCE,
    F110_APPLE_LAYOUT_RHYTHM_COMPLIANCE,
    F001_FORM_SECTION_ORDERING,
    F002_FORM_FIELD_SPACING,
    F003_FORM_WIDGET_APPROPRIATENESS,
    F004_FORM_CANONICAL_PADDING,
    F005_FORM_SINGLE_SCROLL,
];
// Register all invariants
INVARIANTS.forEach(invariant => {
    try {
        const fileName = `F${invariant.code.replace(/^F/, '')}_${invariant.name.replace(/\s+/g, '_').toUpperCase()}.ts`;
        registry.register(invariant, `packages/invariant-engine/src/invariants/ui/${fileName}`);
    }
    catch (error) {
        // Ignore collision errors (invariant already registered)
        if (!(error instanceof Error && (error.message.includes('already exists') || error.message.includes('collision')))) {
            console.error(`Failed to register invariant ${invariant.category}.${invariant.code}:`, error);
        }
    }
});
//# sourceMappingURL=index.js.map